// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/students/presentation/providers/student_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduportfolio/core/domain/entities/student.dart' as _i4;
import 'package:eduportfolio/features/students/domain/usecases/get_all_students_usecase.dart'
    as _i2;
import 'package:eduportfolio/features/students/domain/usecases/get_student_by_id_usecase.dart'
    as _i6;
import 'package:eduportfolio/features/students/domain/usecases/get_students_by_course_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetAllStudentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllStudentsUseCase extends _i1.Mock
    implements _i2.GetAllStudentsUseCase {
  MockGetAllStudentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Student>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<List<_i4.Student>>.value(<_i4.Student>[]),
          )
          as _i3.Future<List<_i4.Student>>);
}

/// A class which mocks [GetStudentsByCourseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStudentsByCourseUseCase extends _i1.Mock
    implements _i5.GetStudentsByCourseUseCase {
  MockGetStudentsByCourseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Student>> call(int? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [courseId]),
            returnValue: _i3.Future<List<_i4.Student>>.value(<_i4.Student>[]),
          )
          as _i3.Future<List<_i4.Student>>);
}

/// A class which mocks [GetStudentByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStudentByIdUseCase extends _i1.Mock
    implements _i6.GetStudentByIdUseCase {
  MockGetStudentByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Student?> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<_i4.Student?>.value(),
          )
          as _i3.Future<_i4.Student?>);
}
