// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/home/presentation/providers/home_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:eduportfolio/core/domain/entities/subject.dart' as _i5;
import 'package:eduportfolio/features/home/domain/usecases/count_pending_evidences_usecase.dart'
    as _i6;
import 'package:eduportfolio/features/home/domain/usecases/get_default_subjects_usecase.dart'
    as _i3;
import 'package:eduportfolio/features/home/domain/usecases/get_storage_info_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageInfo_0 extends _i1.SmartFake implements _i2.StorageInfo {
  _FakeStorageInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDefaultSubjectsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDefaultSubjectsUseCase extends _i1.Mock
    implements _i3.GetDefaultSubjectsUseCase {
  MockGetDefaultSubjectsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Subject>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.Subject>>.value(<_i5.Subject>[]),
          )
          as _i4.Future<List<_i5.Subject>>);
}

/// A class which mocks [CountPendingEvidencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountPendingEvidencesUseCase extends _i1.Mock
    implements _i6.CountPendingEvidencesUseCase {
  MockCountPendingEvidencesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [GetStorageInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStorageInfoUseCase extends _i1.Mock
    implements _i2.GetStorageInfoUseCase {
  MockGetStorageInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StorageInfo> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.StorageInfo>.value(
              _FakeStorageInfo_0(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.StorageInfo>);
}
