// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/sync/presentation/providers/sync_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:camera/camera.dart' as _i4;
import 'package:eduportfolio/core/services/app_settings_service.dart' as _i2;
import 'package:eduportfolio/core/services/sync_password_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsService extends _i1.Mock
    implements _i2.AppSettingsService {
  MockAppSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getImageResolution() =>
      (super.noSuchMethod(
            Invocation.method(#getImageResolution, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> setImageResolution(int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#setImageResolution, [resolution]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResolutionPreset> getResolutionPreset() =>
      (super.noSuchMethod(
            Invocation.method(#getResolutionPreset, []),
            returnValue: _i3.Future<_i4.ResolutionPreset>.value(
              _i4.ResolutionPreset.low,
            ),
          )
          as _i3.Future<_i4.ResolutionPreset>);

  @override
  _i3.Future<int> getVideoResolution() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoResolution, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> setVideoResolution(int? resolution) =>
      (super.noSuchMethod(
            Invocation.method(#setVideoResolution, [resolution]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResolutionPreset> getVideoResolutionPreset() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoResolutionPreset, []),
            returnValue: _i3.Future<_i4.ResolutionPreset>.value(
              _i4.ResolutionPreset.low,
            ),
          )
          as _i3.Future<_i4.ResolutionPreset>);

  @override
  _i3.Future<String?> getSyncServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncServerUrl, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setSyncServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setSyncServerUrl, [url]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSyncServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearSyncServerUrl, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastSyncTimestamp() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTimestamp, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> setLastSyncTimestamp(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSyncTimestamp, [timestamp]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetAllSettings() =>
      (super.noSuchMethod(
            Invocation.method(#resetAllSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SyncPasswordStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncPasswordStorage extends _i1.Mock
    implements _i5.SyncPasswordStorage {
  MockSyncPasswordStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> savePassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#savePassword, [password]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> deletePassword() =>
      (super.noSuchMethod(
            Invocation.method(#deletePassword, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasPassword() =>
      (super.noSuchMethod(
            Invocation.method(#hasPassword, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
