// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/core/data/repositories/course_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduportfolio/core/data/datasources/course_local_datasource.dart'
    as _i2;
import 'package:eduportfolio/core/data/models/course_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CourseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseLocalDataSource extends _i1.Mock
    implements _i2.CourseLocalDataSource {
  MockCourseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CourseModel>> getAllCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCourses, []),
            returnValue: _i3.Future<List<_i4.CourseModel>>.value(
              <_i4.CourseModel>[],
            ),
          )
          as _i3.Future<List<_i4.CourseModel>>);

  @override
  _i3.Future<_i4.CourseModel?> getActiveCourse() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCourse, []),
            returnValue: _i3.Future<_i4.CourseModel?>.value(),
          )
          as _i3.Future<_i4.CourseModel?>);

  @override
  _i3.Future<_i4.CourseModel?> getCourseById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseById, [id]),
            returnValue: _i3.Future<_i4.CourseModel?>.value(),
          )
          as _i3.Future<_i4.CourseModel?>);

  @override
  _i3.Future<int> insertCourse(_i4.CourseModel? course) =>
      (super.noSuchMethod(
            Invocation.method(#insertCourse, [course]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> updateCourse(_i4.CourseModel? course) =>
      (super.noSuchMethod(
            Invocation.method(#updateCourse, [course]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteCourse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourse, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> archiveCourse(int? id, DateTime? endDate) =>
      (super.noSuchMethod(
            Invocation.method(#archiveCourse, [id, endDate]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countCourses() =>
      (super.noSuchMethod(
            Invocation.method(#countCourses, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
