// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/core/data/repositories/evidence_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduportfolio/core/data/datasources/evidence_local_datasource.dart'
    as _i2;
import 'package:eduportfolio/core/data/models/evidence_model.dart' as _i4;
import 'package:eduportfolio/core/domain/entities/evidence.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EvidenceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvidenceLocalDataSource extends _i1.Mock
    implements _i2.EvidenceLocalDataSource {
  MockEvidenceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.EvidenceModel>> getAllEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvidences, []),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudent, [studentId]),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesBySubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesBySubject, [subjectId]),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesByStudentAndSubject(
    int? studentId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudentAndSubject, [
              studentId,
              subjectId,
            ]),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesByType(
    _i5.EvidenceType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByType, [type]),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesNeedingReview() =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesNeedingReview, []),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getUnassignedEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getUnassignedEvidences, []),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<List<_i4.EvidenceModel>> getEvidencesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByDateRange, [startDate, endDate]),
            returnValue: _i3.Future<List<_i4.EvidenceModel>>.value(
              <_i4.EvidenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.EvidenceModel>>);

  @override
  _i3.Future<_i4.EvidenceModel?> getEvidenceById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidenceById, [id]),
            returnValue: _i3.Future<_i4.EvidenceModel?>.value(),
          )
          as _i3.Future<_i4.EvidenceModel?>);

  @override
  _i3.Future<int> insertEvidence(_i4.EvidenceModel? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#insertEvidence, [evidence]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> updateEvidence(_i4.EvidenceModel? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvidence, [evidence]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteEvidence(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvidence, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> assignEvidenceToStudent(int? evidenceId, int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#assignEvidenceToStudent, [
              evidenceId,
              studentId,
            ]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#countEvidences, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesByStudent, [studentId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countEvidencesNeedingReview() =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesNeedingReview, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalStorageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageSize, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
