// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/core/data/repositories/student_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduportfolio/core/data/datasources/student_local_datasource.dart'
    as _i2;
import 'package:eduportfolio/core/data/models/student_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StudentLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentLocalDataSource extends _i1.Mock
    implements _i2.StudentLocalDataSource {
  MockStudentLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.StudentModel>> getAllStudents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllStudents, []),
            returnValue: _i3.Future<List<_i4.StudentModel>>.value(
              <_i4.StudentModel>[],
            ),
          )
          as _i3.Future<List<_i4.StudentModel>>);

  @override
  _i3.Future<List<_i4.StudentModel>> getStudentsByCourse(int? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByCourse, [courseId]),
            returnValue: _i3.Future<List<_i4.StudentModel>>.value(
              <_i4.StudentModel>[],
            ),
          )
          as _i3.Future<List<_i4.StudentModel>>);

  @override
  _i3.Future<List<_i4.StudentModel>> getStudentsFromActiveCourse() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsFromActiveCourse, []),
            returnValue: _i3.Future<List<_i4.StudentModel>>.value(
              <_i4.StudentModel>[],
            ),
          )
          as _i3.Future<List<_i4.StudentModel>>);

  @override
  _i3.Future<_i4.StudentModel?> getStudentById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentById, [id]),
            returnValue: _i3.Future<_i4.StudentModel?>.value(),
          )
          as _i3.Future<_i4.StudentModel?>);

  @override
  _i3.Future<List<_i4.StudentModel>> getStudentsWithFaceData() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsWithFaceData, []),
            returnValue: _i3.Future<List<_i4.StudentModel>>.value(
              <_i4.StudentModel>[],
            ),
          )
          as _i3.Future<List<_i4.StudentModel>>);

  @override
  _i3.Future<List<_i4.StudentModel>> getActiveStudentsWithFaceData() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveStudentsWithFaceData, []),
            returnValue: _i3.Future<List<_i4.StudentModel>>.value(
              <_i4.StudentModel>[],
            ),
          )
          as _i3.Future<List<_i4.StudentModel>>);

  @override
  _i3.Future<int> insertStudent(_i4.StudentModel? student) =>
      (super.noSuchMethod(
            Invocation.method(#insertStudent, [student]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> updateStudent(_i4.StudentModel? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteStudent(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countStudents() =>
      (super.noSuchMethod(
            Invocation.method(#countStudents, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countStudentsByCourse(int? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#countStudentsByCourse, [courseId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
