// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/sync/domain/usecases/sync_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:eduportfolio/features/sync/data/repositories/sync_repository.dart'
    as _i3;
import 'package:eduportfolio/features/sync/domain/entities/sync_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSystemInfo_0 extends _i1.SmartFake implements _i2.SystemInfo {
  _FakeSystemInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_1 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncRepository extends _i1.Mock implements _i3.SyncRepository {
  MockSyncRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> testConnection(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [baseUrl]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.SystemInfo> getSystemInfo(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemInfo, [baseUrl]),
            returnValue: _i4.Future<_i2.SystemInfo>.value(
              _FakeSystemInfo_0(
                this,
                Invocation.method(#getSystemInfo, [baseUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.SystemInfo>);

  @override
  _i4.Future<_i2.SyncResult> syncAll(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, [baseUrl]),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_1(this, Invocation.method(#syncAll, [baseUrl])),
            ),
          )
          as _i4.Future<_i2.SyncResult>);
}
