// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/sync/data/repositories/sync_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:eduportfolio/core/domain/entities/course.dart' as _i10;
import 'package:eduportfolio/core/domain/entities/evidence.dart' as _i14;
import 'package:eduportfolio/core/domain/entities/student.dart' as _i8;
import 'package:eduportfolio/core/domain/entities/subject.dart' as _i12;
import 'package:eduportfolio/core/domain/repositories/course_repository.dart'
    as _i9;
import 'package:eduportfolio/core/domain/repositories/evidence_repository.dart'
    as _i13;
import 'package:eduportfolio/core/domain/repositories/student_repository.dart'
    as _i7;
import 'package:eduportfolio/core/domain/repositories/subject_repository.dart'
    as _i11;
import 'package:eduportfolio/core/services/sync_password_storage.dart' as _i6;
import 'package:eduportfolio/core/services/sync_service.dart' as _i4;
import 'package:eduportfolio/features/sync/domain/entities/sync_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSystemInfo_0 extends _i1.SmartFake implements _i2.SystemInfo {
  _FakeSystemInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncMetadata_1 extends _i1.SmartFake implements _i2.SyncMetadata {
  _FakeSyncMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_2 extends _i1.SmartFake implements _i3.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i4.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setPassword(String? password) => super.noSuchMethod(
    Invocation.method(#setPassword, [password]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.SystemInfo> getSystemInfo(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemInfo, [baseUrl]),
            returnValue: _i5.Future<_i2.SystemInfo>.value(
              _FakeSystemInfo_0(
                this,
                Invocation.method(#getSystemInfo, [baseUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.SystemInfo>);

  @override
  _i5.Future<_i2.SyncMetadata> getMetadata(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, [baseUrl]),
            returnValue: _i5.Future<_i2.SyncMetadata>.value(
              _FakeSyncMetadata_1(
                this,
                Invocation.method(#getMetadata, [baseUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.SyncMetadata>);

  @override
  _i5.Future<void> pushMetadata(String? baseUrl, _i2.SyncMetadata? metadata) =>
      (super.noSuchMethod(
            Invocation.method(#pushMetadata, [baseUrl, metadata]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> uploadFile(
    String? baseUrl,
    _i3.File? file,
    String? filename, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [baseUrl, file, filename],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.File> downloadFile(
    String? baseUrl,
    String? filename,
    String? savePath, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [baseUrl, filename, savePath],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(
                  #downloadFile,
                  [baseUrl, filename, savePath],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<bool> testConnection(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [baseUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> validatePassword(String? baseUrl, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [baseUrl, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SyncPasswordStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncPasswordStorage extends _i1.Mock
    implements _i6.SyncPasswordStorage {
  MockSyncPasswordStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> savePassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#savePassword, [password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> deletePassword() =>
      (super.noSuchMethod(
            Invocation.method(#deletePassword, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasPassword() =>
      (super.noSuchMethod(
            Invocation.method(#hasPassword, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [StudentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentRepository extends _i1.Mock implements _i7.StudentRepository {
  MockStudentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i8.Student>> getAllStudents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllStudents, []),
            returnValue: _i5.Future<List<_i8.Student>>.value(<_i8.Student>[]),
          )
          as _i5.Future<List<_i8.Student>>);

  @override
  _i5.Future<List<_i8.Student>> getStudentsByCourse(int? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByCourse, [courseId]),
            returnValue: _i5.Future<List<_i8.Student>>.value(<_i8.Student>[]),
          )
          as _i5.Future<List<_i8.Student>>);

  @override
  _i5.Future<List<_i8.Student>> getStudentsFromActiveCourse() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsFromActiveCourse, []),
            returnValue: _i5.Future<List<_i8.Student>>.value(<_i8.Student>[]),
          )
          as _i5.Future<List<_i8.Student>>);

  @override
  _i5.Future<_i8.Student?> getStudentById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentById, [id]),
            returnValue: _i5.Future<_i8.Student?>.value(),
          )
          as _i5.Future<_i8.Student?>);

  @override
  _i5.Future<List<_i8.Student>> getStudentsWithFaceData() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsWithFaceData, []),
            returnValue: _i5.Future<List<_i8.Student>>.value(<_i8.Student>[]),
          )
          as _i5.Future<List<_i8.Student>>);

  @override
  _i5.Future<List<_i8.Student>> getActiveStudentsWithFaceData() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveStudentsWithFaceData, []),
            returnValue: _i5.Future<List<_i8.Student>>.value(<_i8.Student>[]),
          )
          as _i5.Future<List<_i8.Student>>);

  @override
  _i5.Future<int> createStudent(_i8.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#createStudent, [student]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateStudent(_i8.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteStudent(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> countStudents() =>
      (super.noSuchMethod(
            Invocation.method(#countStudents, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countStudentsByCourse(int? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#countStudentsByCourse, [courseId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i9.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i10.Course>> getAllCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCourses, []),
            returnValue: _i5.Future<List<_i10.Course>>.value(<_i10.Course>[]),
          )
          as _i5.Future<List<_i10.Course>>);

  @override
  _i5.Future<_i10.Course?> getActiveCourse() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCourse, []),
            returnValue: _i5.Future<_i10.Course?>.value(),
          )
          as _i5.Future<_i10.Course?>);

  @override
  _i5.Future<_i10.Course?> getCourseById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseById, [id]),
            returnValue: _i5.Future<_i10.Course?>.value(),
          )
          as _i5.Future<_i10.Course?>);

  @override
  _i5.Future<int> createCourse(_i10.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#createCourse, [course]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateCourse(_i10.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#updateCourse, [course]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCourse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourse, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> archiveCourse(int? id, DateTime? endDate) =>
      (super.noSuchMethod(
            Invocation.method(#archiveCourse, [id, endDate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unarchiveCourse(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveCourse, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCourseWithFiles(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourseWithFiles, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> countCourses() =>
      (super.noSuchMethod(
            Invocation.method(#countCourses, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [SubjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubjectRepository extends _i1.Mock implements _i11.SubjectRepository {
  MockSubjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i12.Subject>> getAllSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, []),
            returnValue: _i5.Future<List<_i12.Subject>>.value(<_i12.Subject>[]),
          )
          as _i5.Future<List<_i12.Subject>>);

  @override
  _i5.Future<List<_i12.Subject>> getDefaultSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultSubjects, []),
            returnValue: _i5.Future<List<_i12.Subject>>.value(<_i12.Subject>[]),
          )
          as _i5.Future<List<_i12.Subject>>);

  @override
  _i5.Future<_i12.Subject?> getSubjectById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectById, [id]),
            returnValue: _i5.Future<_i12.Subject?>.value(),
          )
          as _i5.Future<_i12.Subject?>);

  @override
  _i5.Future<_i12.Subject?> getSubjectByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectByName, [name]),
            returnValue: _i5.Future<_i12.Subject?>.value(),
          )
          as _i5.Future<_i12.Subject?>);

  @override
  _i5.Future<int> createSubject(_i12.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#createSubject, [subject]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateSubject(_i12.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSubject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> countSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#countSubjects, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [EvidenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvidenceRepository extends _i1.Mock
    implements _i13.EvidenceRepository {
  MockEvidenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i14.Evidence>> getAllEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvidences, []),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudent, [studentId]),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesBySubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesBySubject, [subjectId]),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesByStudentAndSubject(
    int? studentId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudentAndSubject, [
              studentId,
              subjectId,
            ]),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesByType(_i14.EvidenceType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByType, [type]),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesNeedingReview() =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesNeedingReview, []),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getUnassignedEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getUnassignedEvidences, []),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<List<_i14.Evidence>> getEvidencesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByDateRange, [startDate, endDate]),
            returnValue: _i5.Future<List<_i14.Evidence>>.value(
              <_i14.Evidence>[],
            ),
          )
          as _i5.Future<List<_i14.Evidence>>);

  @override
  _i5.Future<_i14.Evidence?> getEvidenceById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidenceById, [id]),
            returnValue: _i5.Future<_i14.Evidence?>.value(),
          )
          as _i5.Future<_i14.Evidence?>);

  @override
  _i5.Future<int> createEvidence(_i14.Evidence? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#createEvidence, [evidence]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateEvidence(_i14.Evidence? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvidence, [evidence]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEvidence(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvidence, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> assignEvidenceToStudent(int? evidenceId, int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#assignEvidenceToStudent, [
              evidenceId,
              studentId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> countEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#countEvidences, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesByStudent, [studentId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countEvidencesNeedingReview({int? courseId}) =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesNeedingReview, [], {
              #courseId: courseId,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getTotalStorageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageSize, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}
