// Mocks generated by Mockito 5.4.6 from annotations
// in eduportfolio/test/unit/features/gallery/domain/usecases/gallery_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eduportfolio/core/domain/entities/evidence.dart' as _i4;
import 'package:eduportfolio/core/domain/repositories/evidence_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EvidenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvidenceRepository extends _i1.Mock
    implements _i2.EvidenceRepository {
  MockEvidenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Evidence>> getAllEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvidences, []),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudent, [studentId]),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesBySubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesBySubject, [subjectId]),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesByStudentAndSubject(
    int? studentId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByStudentAndSubject, [
              studentId,
              subjectId,
            ]),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesByType(_i4.EvidenceType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByType, [type]),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesNeedingReview() =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesNeedingReview, []),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getUnassignedEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#getUnassignedEvidences, []),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<List<_i4.Evidence>> getEvidencesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidencesByDateRange, [startDate, endDate]),
            returnValue: _i3.Future<List<_i4.Evidence>>.value(<_i4.Evidence>[]),
          )
          as _i3.Future<List<_i4.Evidence>>);

  @override
  _i3.Future<_i4.Evidence?> getEvidenceById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvidenceById, [id]),
            returnValue: _i3.Future<_i4.Evidence?>.value(),
          )
          as _i3.Future<_i4.Evidence?>);

  @override
  _i3.Future<int> createEvidence(_i4.Evidence? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#createEvidence, [evidence]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateEvidence(_i4.Evidence? evidence) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvidence, [evidence]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvidence(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvidence, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> assignEvidenceToStudent(int? evidenceId, int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#assignEvidenceToStudent, [
              evidenceId,
              studentId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> countEvidences() =>
      (super.noSuchMethod(
            Invocation.method(#countEvidences, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countEvidencesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesByStudent, [studentId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countEvidencesNeedingReview({int? courseId}) =>
      (super.noSuchMethod(
            Invocation.method(#countEvidencesNeedingReview, [], {
              #courseId: courseId,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalStorageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageSize, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
